// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleTelemetry.Data.Persistance;

#nullable disable

namespace VehicleTelemetry.Migrations
{
    [DbContext(typeof(TelemetryDBContext))]
    partial class TelemetryDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("VehicleTelemetry.Model.TelemetryRecord", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("EngineRpm")
                        .HasColumnType("integer")
                        .HasColumnName("engine_rpm");

                    b.Property<decimal>("FuelLevelPercentage")
                        .HasColumnType("numeric(3,0)")
                        .HasColumnName("fuel_level_percentage");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.HasKey("DeviceId", "Timestamp");

                    b.ToTable("telemetry_record", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
